-- Create a table for ingredients (if you want to move from hardcoded TS to DB)
create table ingredients (
  id text primary key,
  name text not null,
  category text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Master table for conflicts
create table ingredient_conflicts (
  id bigint generated by default as identity primary key,
  ingredient_a_id text references ingredients(id),
  ingredient_b_id text references ingredients(id),
  severity text check (severity in ('High', 'Medium', 'Low')),
  reason text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- User's saved products/routine
create table user_products (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  product_name text not null,
  ingredient_ids text[] not null, -- Array of ingredient IDs contained in product
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table user_products enable row level security;

create policy "Users can view their own products"
  on user_products for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own products"
  on user_products for insert
  with check ( auth.uid() = user_id );
